### ISSUE TITLE
date inidication (as opposed to year indication)

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#104]
DILA has some data expressed using `xsd:date`s with the same semantics as our `onYear`, `notBefore`, `notAfter`. I think a way to accomodate that would be to have:

- `onYear` (range: `xsd:integer`)
- `onDate` (range: `xsd:date`)
- `notBeforeDate` (range: `xsd:date`)
- `notAfterDate` (range: `xsd:date`)
- `notBeforeYear` (range: `xsd:integer`)
- `notAfterYear` (range: `xsd:integer`)

**Comment by eroux** [comment]
two other options:

(2) have `:onDate`, `:notBefore` and `:notAfter` have `xsd:integer or xsd:date` as their range

(3) use only `xsd:date` in `:notBefore` and `notAfter` and change our data to use 1st january or 31 of december, and
(3.1) keep a difference between `:onDate` and `:onYear`
(3.2) encode our data in a different way: when we have `:onYear 2019` we could change it to `:notBefore "2019-01-01"^^xsd:date ; :notAfter "2019-12-31"^^xsd:date`

I tend to lean towards 3.2... wdyt?

**Comment by xristy** [comment]
Hmmm. It seems to me that replacing :onYear ```xsd:integer``` with an interval of ```xsd:date```s would introduce some calculations when displaying just "2019". Since the dataType is carried with the value it should be easy to deal with instances of the union:

    (xsd:integer or xsd:date)

I'm changing the ontology so that ```:notBefore``` and ```:notAfter``` have the union range and adding ```:onDate``` in addition to ```:onYear``` so that there can be labels specific to those two situations.

**Comment by eroux** [comment]
ok perfect, thanks!
