### ISSUE TITLE
example use of :AgentInRole?

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#115]
It seems to me that `:AgentInRole` cannot really be used in the current state of the ontology because there is no property with a range of `:AgentInRole` nor `:AgentOrAgentInRole`.  If I'm mistaken, can you give an example of use?

**Comment by xristy** [comment]
```:AgentInRole``` is a superclass for ```:AgentAsCreator```, which was the initial motivation for this bit of modeling.

The current defined properties are:

    :Work                  :creator    :AgentAsCreator .
    :AgentOrAgentInRole    :role       :Role .
    :AgentInRole           :agent      :Agent .

so that we can express:

    bdr:W12827 a :Work ;
        :creator [ a :AgentAsCreator ;
            :agent bdr:P1583 ;
            :role bdr:MainAuthor ] .

    bdr:MainAuthor a :Role, owl:NamedIndividual .

``` :Role``` instances have not yet been added (but would be like ```bdr:MainAuthor``` or ```bdr:CR001```), and other properties can be added that map from an ```:AgentInRole``` or a subclass for other applications like when the ```:Role```s are the ones being translated by Jann.

**Comment by eroux** [comment]
ok I see, thanks
