### ISSUE TITLE
bdo:sameAsHimalayanArt?

### ISSUE THREAD

**Issue by eroux** [buda-base/owl-schema#137]
the ToL data has some links to Himalayan Art. They are just URLs, not RDF entities and so on, so I'm thinking maybe we could have a subclass of `rdfs:seeAlso` that would be `bdo:seeAlsoHimalayanArt`, with a range of `xsd:anyUri`?

**Comment by xristy** [comment]
we already have been using `rdfs:seeAlso` to link to ToL entries (and others) which aren't presented as RDF resources so we should change the uses of this property to `adm:seeAlso`. The links to Himalayan Art (which can also be useful for deities and so on) can also be `adm:seeAlso`. If this name is too close to `rdfs:seeAlso` then perhaps we could use `adm:seeOther` or `adm:more` or some such.

Upon further examination I realize that there's a minor mess here:

- I modified `rdfs:seeAlso` domain and range inappropriately in 2017
- the `adm:originalRecord` should _not_ be a subProperty of `rdfs:seeAlso`
- using `rdfs:seeAlso` to migrate `<X:external/>` was not appropriate. We should use `adm:seeOther` or whatever.

Note there is also a property, `bdo:seeAlso` that is unused and deprecated and that I will remove now.

**Comment by eroux** [comment]
I was thinking of using the same system we have for `owl:sameAs` where we just make subproperties for the various datasets. It's interesting because it allows us to display the various links differently (with the icon of the corresponding dataset for instance), so I think we should have a version of seeAlso that's specific to Himalayan Art... wdyt?

The links to ToL should be replaced with `adm:sameAsToL` BTW, as they'll have RDF entities. These have different URIs so in the migration process I think we should just ignore the ToL see also, and add the correct links in a batch update later.

**Comment by xristy** [comment]
We currently have:

- `owl:sameAs` :  `owl:Thing ==> owl:Thing`
  - `bdo:sameAsrKTs`: used
  - `bdo:sameAsToL`: not used, but will replace `adm:seeOtherToL`
  - `bdo:sameAsVIAF`: used once for P6161
  - `bdo:sameAsWikidata`: not used
  - `bdo:sameAsWorldCat`: not used

I think it's appropriate to change the above to `adm:` since they are comments on other metadata versus the RWO.

For now since we do have links to ToL I propose to continue to migrate them and replace when the RDF LoD is ready. We can use a hierarchy like:

- `adm:seeOther`:  `bdo:Entity ==> xsd:AnyURI`
  - `adm:seeOtherToL`
  - `adm:seeOtherHA`

and use an annotation like a shacl constraint to indicate the `adm:Organization` that a subProperty of `owl:sameAs` and `adm:seeOther` are associated with

**Comment by eroux** [comment]
looks good to me, the only small puzzlement I have is why we need an `adm:seeOther`? Can't we have just `adm:seeOtherToL` be a subclass of `rdfs:seeAlso`?

**Comment by xristy** [comment]
I don't think we should. Per [`rdfs:seeAlso`](https://www.w3.org/TR/rdf-schema/#ch_seealso):

```
rdfs:seeAlso :  rdfs:Resource ==> rdfs:Resource
```
so we define the property `adm:seeOther`:

```
adm:seeOther :  bdo:Entity ==> xsd:AnyURI
```
Since the URLs don't (necessarily) point to RDF resources.

Also in your comment do you also agree with re-locating `bdo:sameAsrKTs` and siblings to the `adm:` namespace?
